#Daniel Vinakovsky
#CS-115 - Homework 11
#10 December 2013
#I pledge my honor that I have abided by the Stevens Honor System

from Shapes import *

def main():
	lwheel = Circle(radius=2,center=Vector(50,-300),color="brown")
	rwheel = Circle(radius=2,center=Vector(125,-300),color="brown")
	board = Rectangle(width=80,height=3,center=Vector(87.5,-296),color="black")
	ramp = rTriangle(base=300,height=125,center=Vector(-300,-260),color="orange")
	lleg = Rectangle(width=4,height=85,center=Vector(75,-251),color="blue")
	rleg = Rectangle(width=4,height=85,center=Vector(105,-251),color="blue")
	torso = Rectangle(width=50,height=100,center=Vector(90,-210),color="red")
	larm = Rectangle(width=1,height=60,center=Vector(75,-210),color="blue")
	rarm = Rectangle(width=1,height=60,center=Vector(115,-210),color="blue")
	head = Circle(radius=20,center=Vector(90,-130),color="green")
	sun= Circle(radius=100,center=Vector(400,400),color="yellow")
	
	turtle.speed(0)
	
	lwheel.render()
	rwheel.render()
	board.render()
	ramp.render()
	lleg.render()
	rleg.render()
	torso.render()
	head.render()
	sun.render()
	
	sun.scale(2.0)
	sun.translate(Vector(400,400))
	sun.render()
	
	larm.rotate(200)
	larm.translate(Vector(197,-325))
	larm.render()
	rarm.rotate(160)
	rarm.translate(Vector(163,-390))
	rarm.render()
	
	
	ramp.erase()
	ramp.translate(Vector(33,0))
	ramp.render()
	ramp.erase()
	ramp.translate(Vector(33,0))
	ramp.render()
	ramp.erase()
	ramp.translate(Vector(33,0))
	ramp.render()
	ramp.erase()
	ramp.translate(Vector(33,0))
	ramp.render()
	ramp.erase()
	ramp.translate(Vector(33,0))
	ramp.render()
	ramp.erase()
	ramp.translate(Vector(33,0))
	ramp.render()
	ramp.erase()
	ramp.translate(Vector(50,0))
	ramp.render()
	ramp.erase()
	ramp.rotate(20)
	ramp.translate(Vector(0,-40))
	ramp.render()
	ramp.erase()
	ramp.rotate(2)
	ramp.translate(Vector(10,-3))
	ramp.render()
	ramp.erase()
	ramp.translate(Vector(50,-1))
	ramp.render()
	ramp.erase()
	ramp.translate(Vector(50,-1))
	ramp.render()
	
	lwheel.erase()
	rwheel.erase()
	larm.erase()
	rarm.erase()
	board.erase()
	lleg.erase()
	rleg.erase()
	torso.erase()
	head.erase()
	
	lwheel.translate(Vector(-48,-281))
	rwheel.translate(Vector(25,-281))
	larm.translate(Vector(-100,20))
	rarm.translate(Vector(-100,20))
	board.translate(Vector(-100,20))
	lleg.translate(Vector(-100,20))
	rleg.translate(Vector(-100,20))
	torso.translate(Vector(-100,20))
	head.translate(Vector(-11,-109))
	
	ramp.erase()
	ramp.rotate(-23)
	ramp.translate(Vector(200,0))
	ramp.render()
	
	lwheel.render()
	rwheel.render()
	larm.render()
	rarm.render()
	board.render()
	lleg.render()
	rleg.render()
	torso.render()
	head.render()
	
	ramp.erase()
	ramp.translate(Vector(15,25))
	ramp.render()
	ramp.erase()
	ramp.translate(Vector(15,25))
	ramp.render()
	ramp.erase()
	ramp.translate(Vector(15,25))
	ramp.render()
	ramp.erase()
	ramp.translate(Vector(15,25))
	ramp.render()
	
	turtle.exitonclick()
	
main()